image: node:8

stages:
  - build
  - test
  - deploy

before_script:
  - npm install --silent

cache:
    paths:
    - ./node_modules

build:
  script:
    - npm run build:gitlab
  artifacts:
    paths:
      - dist/

test:
  before_script:
    # Add Google Chrome to aptitude's (package manager) sources
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list
    # Fetch Chrome's PGP keys for secure installation
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    # Update aptitude's package sources
    - apt-get -qq update -y
    # Install latest Chrome stable, Xvfb packages
    - apt-get -qq install -y google-chrome-stable xvfb gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable imagemagick x11-apps default-jre
    # Launch Xvfb
    - Xvfb :0 -ac -screen 0 1024x768x24 &
    # Export display for Chrome
    - export DISPLAY=:99
    # Download Selenium server JAR, drivers for Chrome
    - node ./node_modules/.bin/webdriver-manager update
  script:
    - npm run lint
    - npm run test:chromeHeadless
    - npm run e2e

pages:
  stage: deploy
  script:
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master